services:
  trudesk:
    image: flycatch/trudesk
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8118:8118"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
      TD_TRUST_PROXY: "${TD_TRUST_PROXY:-false}"
    volumes:
      - trudesk_uploads:/usr/src/trudesk/public/uploads
      - trudesk_backups:/usr/src/trudesk/backups
    networks:
      - trudesk
      - trudesk-elk
  mongo:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - mongo:/var/lib/mongo
      - mongo_data:/data/db:rw
    networks:
      - trudesk
  elasticsearch:
    image: elasticsearch:8.0.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - trudesk-elk

  fake-smtp-server:
    container_name: trudesk-fake-smtp-server
    image: rnwood/smtp4dev
    restart: on-failure
    ports:
      - "3010:80"
    profiles:
      - dev
    networks:
      - trudesk
  kibana:
    image: kibana:8.0.0
    restart: always
    ports:
      - 5601:5601
    profiles:
      - dev
    environment:
      SERVER_NAME: "kibana:5601"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - trudesk-elk
volumes:
  trudesk_uploads:
  trudesk_backups:
  mongo:
  mongo_data:
  elasticsearch:
networks:
  trudesk:
    name: trudesk
  trudesk-elk:
    name: trudesk-elk
